import type {
  AssessmentDocQuery,
  AssessmentDocument,
  AssessmentDocType
} from '@/types/assessment-score';

function pad(n: number) {
  return String(n).padStart(2, '0');
}

function formatDateTime(d: Date) {
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
}

function cloneDoc(doc: AssessmentDocument): AssessmentDocument {
  return { ...doc };
}

/** 红黄旗：每月 2 号 09:00 自动生成 */
function redYellowGenerateAt(year: number, month: number) {
  return formatDateTime(new Date(year, month - 1, 2, 9, 0, 0));
}

/** 季度考核：季末当日 18:00 自动生成 */
function quarterlyGenerateAt(year: number, quarter: number) {
  const endMonth = quarter * 3;
  const endDay = new Date(year, endMonth, 0).getDate();
  return formatDateTime(new Date(year, endMonth - 1, endDay, 18, 0, 0));
}

/** 年度考核：年末 12 月 31 日 18:00 自动生成 */
function annualGenerateAt(year: number) {
  return formatDateTime(new Date(year, 11, 31, 18, 0, 0));
}

function fileSizeFor(seed: string) {
  let hash = 0;
  for (let i = 0; i < seed.length; i += 1) {
    hash = (hash * 31 + seed.charCodeAt(i)) >>> 0;
  }
  return 180000 + (hash % 420000);
}

function makeRedYellowDoc(year: number, month: number): AssessmentDocument {
  const periodLabel = `${year}年${month}月`;
  return {
    id: `ryf-${year}-${pad(month)}`,
    type: 'red_yellow_flag',
    periodLabel,
    year,
    month,
    fileName: `红黄旗评分表_${year}年${pad(month)}月.pdf`,
    fileSize: fileSizeFor(`ryf-${year}-${month}`),
    generatedAt: redYellowGenerateAt(year, month),
    generateRule: '每月2日系统自动生成并存档'
  };
}

function makeQuarterlyDoc(year: number, quarter: number): AssessmentDocument {
  const quarterNames = ['一季度', '二季度', '三季度', '四季度'] as const;
  const quarterName = quarterNames[quarter - 1];
  const periodLabel = `${year}年${quarterName}`;
  return {
    id: `qtr-${year}-Q${quarter}`,
    type: 'quarterly',
    periodLabel,
    year,
    quarter,
    fileName: `季度考核评分表_${year}年${quarterName}.pdf`,
    fileSize: fileSizeFor(`qtr-${year}-${quarter}`),
    generatedAt: quarterlyGenerateAt(year, quarter),
    generateRule: '每季度末系统自动生成并存档'
  };
}

function makeAnnualDoc(year: number): AssessmentDocument {
  const periodLabel = `${year}年度`;
  return {
    id: `year-${year}`,
    type: 'annual',
    periodLabel,
    year,
    fileName: `年度考核评分表_${year}年.pdf`,
    fileSize: fileSizeFor(`year-${year}`),
    generatedAt: annualGenerateAt(year),
    generateRule: '每年末系统自动生成并存档'
  };
}

/**
 * 按当前时间补齐已到期应自动生成的文档：
 * - 红黄旗：每月 2 号及之后生成当月文档
 * - 季度：季末日及之后生成当季文档
 * - 年度：12 月 31 日及之后生成当年文档
 */
function buildAutoGeneratedDocs(now = new Date()): AssessmentDocument[] {
  const docs: AssessmentDocument[] = [];
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());

  // 红黄旗：回溯约 14 个月（满足 11–15 条展示）
  for (let offset = 0; offset < 14; offset += 1) {
    const d = new Date(now.getFullYear(), now.getMonth() - offset, 1);
    const year = d.getFullYear();
    const month = d.getMonth() + 1;
    const genDay = new Date(year, month - 1, 2);
    if (today >= genDay) {
      docs.push(makeRedYellowDoc(year, month));
    }
  }

  // 季度：回溯约 8 个季度
  for (let offset = 0; offset < 8; offset += 1) {
    const abs = now.getFullYear() * 4 + Math.floor(now.getMonth() / 3) - offset;
    const year = Math.floor(abs / 4);
    const quarter = (abs % 4) + 1;
    const endMonth = quarter * 3;
    const endDay = new Date(year, endMonth, 0).getDate();
    const genDay = new Date(year, endMonth - 1, endDay);
    if (today >= genDay) {
      docs.push(makeQuarterlyDoc(year, quarter));
    }
  }

  // 年度：回溯近 3 年（已过年末才生成）
  for (let offset = 1; offset <= 3; offset += 1) {
    const year = now.getFullYear() - offset;
    docs.push(makeAnnualDoc(year));
  }
  // 若已到当年年末，也生成当年年度考核
  if (today >= new Date(now.getFullYear(), 11, 31)) {
    docs.push(makeAnnualDoc(now.getFullYear()));
  }

  return docs;
}

const records: AssessmentDocument[] = buildAutoGeneratedDocs();

function matchKeyword(doc: AssessmentDocument, keyword?: string) {
  if (!keyword?.trim()) return true;
  const kw = keyword.trim().toLowerCase();
  return (
    doc.periodLabel.toLowerCase().includes(kw) ||
    doc.fileName.toLowerCase().includes(kw) ||
    doc.generateRule.toLowerCase().includes(kw)
  );
}

export const assessmentScoreStore = {
  list(params?: AssessmentDocQuery) {
    let list = records.map(cloneDoc);

    if (params?.type) {
      list = list.filter((d) => d.type === params.type);
    }
    if (params?.category === 'annual') {
      list = list.filter((d) => d.type === 'annual');
    } else if (params?.category === 'quarterly') {
      list = list.filter((d) => d.type === 'quarterly');
    }
    if (params?.year != null) {
      list = list.filter((d) => d.year === params.year);
    }
    if (params?.keyword) {
      list = list.filter((d) => matchKeyword(d, params.keyword));
    }

    return list.sort((a, b) => (a.generatedAt < b.generatedAt ? 1 : -1));
  },

  getById(id: string) {
    const item = records.find((d) => d.id === id);
    return item ? cloneDoc(item) : undefined;
  },

  /** 演示：按规则触发补齐（页面进入时可调用） */
  ensureGenerated(now = new Date()) {
    const fresh = buildAutoGeneratedDocs(now);
    for (const doc of fresh) {
      if (!records.some((r) => r.id === doc.id)) {
        records.push(doc);
      }
    }
  },

  types(): AssessmentDocType[] {
    return ['red_yellow_flag', 'annual', 'quarterly'];
  }
};
