import type {
  LetterDocQuery,
  LetterDocument,
  LetterDocType
} from '@/types/two-letters-one-order';
import { LETTER_DOC_TYPE_LABEL } from '@/types/two-letters-one-order';

function pad(n: number) {
  return String(n).padStart(2, '0');
}

function formatDateTime(d: Date) {
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
}

function cloneDoc(doc: LetterDocument): LetterDocument {
  return { ...doc };
}

/** 两函一单：每月 2 号 09:00 自动生成 */
function monthlyGenerateAt(year: number, month: number) {
  return formatDateTime(new Date(year, month - 1, 2, 9, 0, 0));
}

function fileSizeFor(seed: string) {
  let hash = 0;
  for (let i = 0; i < seed.length; i += 1) {
    hash = (hash * 31 + seed.charCodeAt(i)) >>> 0;
  }
  return 160000 + (hash % 380000);
}

function makeLetterDoc(type: LetterDocType, year: number, month: number): LetterDocument {
  const label = LETTER_DOC_TYPE_LABEL[type];
  const periodLabel = `${year}年${month}月`;
  return {
    id: `${type}-${year}-${pad(month)}`,
    type,
    periodLabel,
    year,
    month,
    fileName: `${label}_${year}年${pad(month)}月.pdf`,
    fileSize: fileSizeFor(`${type}-${year}-${month}`),
    generatedAt: monthlyGenerateAt(year, month),
    generateRule: '每月2日系统自动生成并存档'
  };
}

/**
 * 按当前时间补齐已到期应自动生成的文档：
 * 每月 2 号及之后生成当月交办函 / 提醒函 / 督办函
 */
function buildAutoGeneratedDocs(now = new Date()): LetterDocument[] {
  const docs: LetterDocument[] = [];
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const types: LetterDocType[] = ['assign', 'remind', 'supervise'];

  for (let offset = 0; offset < 14; offset += 1) {
    const d = new Date(now.getFullYear(), now.getMonth() - offset, 1);
    const year = d.getFullYear();
    const month = d.getMonth() + 1;
    const genDay = new Date(year, month - 1, 2);
    if (today >= genDay) {
      for (const type of types) {
        docs.push(makeLetterDoc(type, year, month));
      }
    }
  }

  return docs;
}

const records: LetterDocument[] = buildAutoGeneratedDocs();

export const twoLettersOneOrderStore = {
  list(params?: LetterDocQuery) {
    let list = records.map(cloneDoc);

    if (params?.type) {
      list = list.filter((d) => d.type === params.type);
    }
    if (params?.year != null) {
      list = list.filter((d) => d.year === params.year);
    }
    if (params?.month != null) {
      list = list.filter((d) => d.month === params.month);
    }

    return list.sort((a, b) => (a.generatedAt < b.generatedAt ? 1 : -1));
  },

  getById(id: string) {
    const item = records.find((d) => d.id === id);
    return item ? cloneDoc(item) : undefined;
  },

  ensureGenerated(now = new Date()) {
    const fresh = buildAutoGeneratedDocs(now);
    for (const doc of fresh) {
      if (!records.some((r) => r.id === doc.id)) {
        records.push(doc);
      }
    }
  }
};
